name: CG22
description: "APK para control de gastos"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+3
  path: ^1.8.3
  path_provider: ^2.0.11
  intl: ^0.18.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icono/G22_icon_512x512.png

flutter_icons: # <-- Esta parte va FUERA del bloque `flutter`
  android: true
  ios: true
  image_path: "assets/icono/G22_icon_512x512.png"

